"use client";
import React, { useState } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar/page";
import Slider from "./component/slider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const cards = [
  {
    name: "flower1",
    url: "https://images.pexels.com/photos/697259/pexels-photo-697259.jpeg?cs=srgb&dl=pexels-hi%E1%BA%BFu-ho%C3%A0ng-697259.jpg&fm=jpg",
  },
  {
    name: "flower2",
    url: "https://cdn.britannica.com/84/73184-050-05ED59CB/Sunflower-field-Fargo-North-Dakota.jpg",
  },
  {
    name: "flower3",
    url: "https://images.pexels.com/photos/697259/pexels-photo-697259.jpeg?cs=srgb&dl=pexels-hi%E1%BA%BFu-ho%C3%A0ng-697259.jpg&fm=jpg",
  },
  {
    name: "flower4",
    url: "https://cdn.britannica.com/84/73184-050-05ED59CB/Sunflower-field-Fargo-North-Dakota.jpg",
  },
  {
    name: "flower5",
    url: "https://img.freepik.com/free-photo/vibrant-colors-nature-close-up-wet-purple-daisy-generated-by-artificial-intellingence_25030-63819.jpg",
  },
  {
    name: "flower6",
    url: "https://cdn.britannica.com/84/73184-050-05ED59CB/Sunflower-field-Fargo-North-Dakota.jpg",
  },
];
export { cards };
export default function RootLayout({ children }) {
  const [open, setOpen] = useState(false);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar open={open} setOpen={setOpen} />
        <Slider cards={cards} open={open} setOpen={setOpen} />
        {React.Children.map(children, (child) =>
          React.cloneElement(child, { dataProp: cards })
        )}
      </body>
    </html>
  );
}
